# Generated by Django 2.1.5 on 2019-01-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20190124_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tap_set',
            field=models.ManyToManyField(blank=True, to='blog_app.Tag'),
        ),
    ]
